<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Formas de Pagamento_icone-meio-pagamento img-icone-pix</name>
   <tag></tag>
   <elementGuidId>e2cad24f-1897-4b55-a304-22e24d2609a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div[2]/div/div[3]/div/a/div/em</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>em.icone-meio-pagamento.img-icone-pix</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>c88708f3-570b-4c30-87f2-5aa3e0fbff8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icone-meio-pagamento img-icone-pix</value>
      <webElementGuid>fc4ae645-13d4-4585-8bde-6feaab32ec9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;container-fluid novo-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-6&quot;]/div[@class=&quot;container-fluid mt-1 pl-0 pr-0 meios-conteudo mb-3&quot;]/div[@class=&quot;row mt-0 mt-sm-1&quot;]/div[@class=&quot;d-flex&quot;]/a[@class=&quot;meio-pagamento-a ml-2 ml-sm-0 mr-0 mr-sm-2 mt-2 mt-sm-0&quot;]/div[@class=&quot;meio-pagamento&quot;]/em[@class=&quot;icone-meio-pagamento img-icone-pix&quot;]</value>
      <webElementGuid>44b50c82-0e46-4ecd-adb7-c02a6976af13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SIPAC - Sistema Integrado de Patrimnio_f8a443/iframe_Entrar no sistema_iFrameResizer0</value>
      <webElementGuid>f8774faa-9649-419f-8b9d-aa044ae88c6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div[2]/div/div[3]/div/a/div/em</value>
      <webElementGuid>71fa1ffc-a4b1-4ba3-83d9-04626e022b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//em</value>
      <webElementGuid>b88e8571-9d2b-474c-92a5-f03700feba82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
