<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Entrar no sistema_iFrameResizer0</name>
   <tag></tag>
   <elementGuidId>a7fbcac2-6c6b-470c-9b3c-0c888841cf8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iFrameResizer0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iFrameResizer0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>88a65e29-f084-4c6d-b1bc-48156e1c890b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframe-epag</value>
      <webElementGuid>0ba6e761-d61e-4403-89b1-5fd8fdf61d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://pagtesouro.tesouro.gov.br/#/pagamento?idSessao=e5b7ad0a-3975-4d91-a38f-72f851b36f9c&amp;tema=tema-light&amp;btnConcluir=true</value>
      <webElementGuid>f8e48602-d347-4c02-9aa9-5ffb080f73cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>660b5018-f3f7-4453-8ae2-cd5b70e28cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iFrameResizer0</value>
      <webElementGuid>6df9f1b3-affa-4ced-9023-f0d913bb481d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iFrameResizer0&quot;)</value>
      <webElementGuid>cfacb792-1aaf-4cd4-8769-75d64d1b35f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iFrameResizer0']</value>
      <webElementGuid>e5b78e88-ba07-421a-85d7-a6e62e2b8352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corpo']/iframe</value>
      <webElementGuid>fe14187a-88ac-4558-99c6-9879be00c80c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entrar no sistema'])[1]/following::iframe[1]</value>
      <webElementGuid>2f2e1ff5-8ff7-43be-a079-0bf384ffa43b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/html[1]'])[1]/preceding::iframe[1]</value>
      <webElementGuid>760d5be0-3bd5-4e2d-9dfc-9e7e547a031a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>edbcb8c1-b2ff-4cd2-888b-f9e293559912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://pagtesouro.tesouro.gov.br/#/pagamento?idSessao=e5b7ad0a-3975-4d91-a38f-72f851b36f9c&amp;tema=tema-light&amp;btnConcluir=true' and @id = 'iFrameResizer0']</value>
      <webElementGuid>766c0134-d505-48c9-be8c-ed0a499650a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
