<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Quantidade de Crditos_formqtdCreditos</name>
   <tag></tag>
   <elementGuidId>594eee5d-75fe-4b9e-8b11-b39f7f0a51e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form:qtdCreditos']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b827b01-5fff-4be1-92de-fef5d64df933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form:qtdCreditos</value>
      <webElementGuid>82678248-3ccd-4161-99eb-d378b6fc71bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>09bdec1b-85d7-48e9-a143-7d7911ef1402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form:qtdCreditos</value>
      <webElementGuid>85f39300-f657-4d0d-a5c1-ca74ccdb0f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ebe5b068-93f6-46dc-b44c-ff2c2b984ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a95984d2-92b1-46bd-918d-35d0cbd799dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('form',event,{'similarityGroupingId':'form:j_id_jsp_540432864_3','parameters':{'form:j_id_jsp_540432864_3':'form:j_id_jsp_540432864_3'} ,'containerId':'j_id_jsp_540432864_0'} )</value>
      <webElementGuid>92772552-8c32-4eb1-a9ea-a9b8398e23a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>return formatarInteiro(this)</value>
      <webElementGuid>d40953b4-ec05-422e-848c-1a266a78c17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>c15a28b3-a876-44fb-9c1c-d697cf2774dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form:qtdCreditos&quot;)</value>
      <webElementGuid>98698933-a204-4953-9c2d-c1d78f6d12c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form:qtdCreditos']</value>
      <webElementGuid>c73eafe2-1f18-4eee-acea-872bd05221f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/table[2]/tbody/tr/td/input</value>
      <webElementGuid>884bae41-d885-4512-9cb4-089cdb3cfe57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>63749bfc-bdc2-4590-9719-2e40a028b477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'form:qtdCreditos' and @type = 'text' and @name = 'form:qtdCreditos']</value>
      <webElementGuid>b952eba5-e793-477e-87bb-0143624bf3d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
