<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero do carto_formj_id_jsp_1091681061_2</name>
   <tag></tag>
   <elementGuidId>8444e80f-b766-453b-9fb5-bfaa26c1aee5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='form:j_id_jsp_1091681061_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;form:j_id_jsp_1091681061_2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb58ad00-ae8b-4f82-a71c-25e9da8bd354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1463ff7f-c59d-4f34-94df-44dbebf659d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form:j_id_jsp_1091681061_2</value>
      <webElementGuid>de7016a8-3a2f-4f18-9dc4-043bc89b23e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>a30e0779-06c0-4563-a025-7b474838e1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return apenasNumeros(event)</value>
      <webElementGuid>32126aa7-cfdc-4f0f-a09d-a9e74da102f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>70</value>
      <webElementGuid>719062a4-354f-4dc5-9e88-e9044e3e7b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/table[@class=&quot;formulario&quot;]/tbody[1]/tr[1]/td[1]/input[1]</value>
      <webElementGuid>b9b87a14-a192-44cb-bb30-aeb284c3b150</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='form:j_id_jsp_1091681061_2']</value>
      <webElementGuid>46f6401d-faa3-446b-b208-e6dc2a4adfb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/table/tbody/tr/td/input</value>
      <webElementGuid>f6f6a752-dba7-4bb0-b90a-1f131f001b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>42d8e47e-fdce-4089-981e-3aa2bf0b78f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'form:j_id_jsp_1091681061_2']</value>
      <webElementGuid>a7ffe30c-04d0-46b5-8f1a-2324fa15e98f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
