<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_GRU_formbtPagTesouro</name>
   <tag></tag>
   <elementGuidId>3847b464-83b7-4452-9cb3-e6940b677189</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form:btPagTesouro']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c92b3497-31d2-4e5c-93ee-cf4490dd7d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form:btPagTesouro</value>
      <webElementGuid>1b0e10ca-24ed-4ed5-a70b-5ee7488ebaee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>791b7ff4-755d-4ad9-a737-40a9398bb142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form:btPagTesouro</value>
      <webElementGuid>3a62c31f-10b4-4846-abd4-f4d0b3b51458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pagar</value>
      <webElementGuid>219fc75a-7084-4fd9-aa31-47f0bc8ffd7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>a1ce955c-17df-445d-b5e9-d47c5f4821a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form:btPagTesouro&quot;)</value>
      <webElementGuid>8dc73768-da0c-4883-ab18-0022f7dd9d45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form:btPagTesouro']</value>
      <webElementGuid>6f05de74-ed80-4f5d-88e2-aaa2225b86fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form:formaPagamentoSelecionada_body']/input</value>
      <webElementGuid>ca97911b-de4c-4621-9a65-a28bef0fa787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>db219992-7d0d-4ab4-ac0d-cdde398a7859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'form:btPagTesouro' and @type = 'submit' and @name = 'form:btPagTesouro']</value>
      <webElementGuid>8ed5e566-5997-4ad3-b2b1-2ffa15886952</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
