<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total a Pagar (R)_formj_id_jsp_540432864_5</name>
   <tag></tag>
   <elementGuidId>69b67c41-6c62-4644-bb2c-13bdb31e5114</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form:j_id_jsp_540432864_5:0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c13e3803-67c3-4a1f-9898-5700743114fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>05f98aa6-8cec-47b8-81f1-5721b60a4fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form:j_id_jsp_540432864_5</value>
      <webElementGuid>659a6ca9-36d9-4c3c-a2dc-46450d699bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form:j_id_jsp_540432864_5:0</value>
      <webElementGuid>7b507afb-0bc5-4c8d-b1d3-553a0e4676d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>14df47ce-c643-4fcc-a638-977d907b484a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('form',event,{'similarityGroupingId':'form:j_id_jsp_540432864_8','parameters':{'form:j_id_jsp_540432864_8':'form:j_id_jsp_540432864_8'} ,'containerId':'j_id_jsp_540432864_0'} )</value>
      <webElementGuid>ede09576-632a-4f48-bdc8-12028d90596f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form:j_id_jsp_540432864_5:0&quot;)</value>
      <webElementGuid>bc5b786f-3d39-42c3-b2c3-0d35b40fc1a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form:j_id_jsp_540432864_5:0']</value>
      <webElementGuid>b674d693-32a8-423e-84e6-c2a052a55786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/table[2]/tbody/tr[3]/td/table/tbody/tr/td/input</value>
      <webElementGuid>d97cfb21-d861-4021-bbe2-34712b39f05d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td/input</value>
      <webElementGuid>06e8723c-4811-4c69-b601-1e0ef680c1b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'form:j_id_jsp_540432864_5' and @id = 'form:j_id_jsp_540432864_5:0']</value>
      <webElementGuid>4f67cc00-ff01-481d-b51f-6a5a647dd4bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
