<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Campos de preenchimento obrigatrio_fo_328bc9</name>
   <tag></tag>
   <elementGuidId>bc2a7a83-3a26-496d-b7ca-e3c5a39c8886</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='form:j_id_jsp_1091681061_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;form:j_id_jsp_1091681061_4&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a02bf62-78c7-457a-9f14-ace8798f4d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c1a90c12-c220-4bc3-a16c-707cdecc5d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form:j_id_jsp_1091681061_4</value>
      <webElementGuid>6930e564-7e92-40a4-970f-8ad94b8ca98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Consultar</value>
      <webElementGuid>135bdae6-7b7a-4ecf-9090-6a5e8af9a0f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/table[@class=&quot;formulario&quot;]/tfoot[1]/tr[1]/td[1]/input[1]</value>
      <webElementGuid>bd18cb47-b94d-439a-a00f-3a2f1deaedee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='form:j_id_jsp_1091681061_4']</value>
      <webElementGuid>1f00565e-c1c3-4b68-8836-8858ecc118c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/table/tfoot/tr/td/input</value>
      <webElementGuid>a8569a4e-813d-404a-b4ea-97fc0838b1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tfoot/tr/td/input</value>
      <webElementGuid>7e20442d-b3c3-4b66-834f-a36e77b9fdb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'form:j_id_jsp_1091681061_4']</value>
      <webElementGuid>21cb4bbd-6f99-4c4e-a93e-f537cb3a3da9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
