<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Matrcula atrelada ao carto_formj_id_j_2c591d</name>
   <tag></tag>
   <elementGuidId>e979c469-9450-41af-a531-a24c57f59390</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='form:j_id_jsp_1091681061_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;form:j_id_jsp_1091681061_3&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e46d4776-c441-4a01-b007-45c6cc5dff2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b736e142-4650-4301-ad8d-95d247ad8abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form:j_id_jsp_1091681061_3</value>
      <webElementGuid>4922c2e2-db8f-4938-a318-fdf9c2fa1e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>8a1c71e6-934b-489c-a9b6-c227bbb5111e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return apenasNumeros(event)</value>
      <webElementGuid>1fa3c165-6a18-4d21-a209-dca31492ad70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>70</value>
      <webElementGuid>700c93fa-16b2-49f1-b765-f6879ad61b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/table[@class=&quot;formulario&quot;]/tbody[1]/tr[2]/td[1]/input[1]</value>
      <webElementGuid>8ecf62ed-be03-45d5-8e6d-b973ff827495</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='form:j_id_jsp_1091681061_3']</value>
      <webElementGuid>f553ec84-96d3-429b-b540-c019db738151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/table/tbody/tr[2]/td/input</value>
      <webElementGuid>60d60bf7-3cf2-4584-9ff4-300fecd37aae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>87e2f929-d3d9-4e8b-bb19-372dfe42ef05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'form:j_id_jsp_1091681061_3']</value>
      <webElementGuid>3a025ac7-a720-4da6-a979-d28fae8c509f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
