<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ATENO_modalForm2btConfirmarPagtesouro</name>
   <tag></tag>
   <elementGuidId>72cf8f70-5f06-4536-9624-294a2ce595f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='modalForm2:btConfirmarPagtesouro']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5afd735-6f38-4461-b5c2-6c6ae43bf466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modalForm2:btConfirmarPagtesouro</value>
      <webElementGuid>af6a04b5-96f1-4cc1-98d1-a9825b0d28cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f0d51bb6-4e8f-4080-8ad9-029de2d3b0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>modalForm2:btConfirmarPagtesouro</value>
      <webElementGuid>0252379c-757e-4716-af88-17ed793f0354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Estou ciente</value>
      <webElementGuid>b805f7ab-35b8-4cc0-96c4-1cb1089d3a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalForm2:btConfirmarPagtesouro&quot;)</value>
      <webElementGuid>58203b8e-a7d3-40f5-8529-c375e971d850</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='modalForm2:btConfirmarPagtesouro']</value>
      <webElementGuid>28004d70-9cfe-4fc9-865e-65c8db182c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='modalForm2']/div[2]/input</value>
      <webElementGuid>78fe323e-0f7a-4bdc-b996-c16d7f15d59a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div[2]/table/tbody/tr[2]/td/span/form/div[2]/input</value>
      <webElementGuid>88306853-8d8e-4800-991d-fb3aad9f4c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'modalForm2:btConfirmarPagtesouro' and @type = 'submit' and @name = 'modalForm2:btConfirmarPagtesouro']</value>
      <webElementGuid>a38fce58-09ae-4049-97b3-e6120dd251bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
